CREATE or replace PROCEDURE fill_names_surnames()
    LANGUAGE plpgsql
AS
$$
BEGIN
    CREATE TEMPORARY TABLE names
    (
        name_id serial PRIMARY KEY,
        name    varchar(30)
    );

    CREATE TEMPORARY TABLE surnames
    (
        surname_id serial PRIMARY KEY,
        surname    varchar(30)
    );

    COPY names (name)
        FROM '/docker-entrypoint-initdb.d/csv/names.csv'
        DELIMITER ',';
    COPY surnames (surname)
        FROM '/docker-entrypoint-initdb.d/csv/surnames.csv'
        DELIMITER ',';
END;
$$;

create or replace function fill_car_model() returns void
    language plpgsql
as
$$
declare
    brands_count integer = (select count(*)
                            from brands);

begin
    create temporary sequence car_model_seq start 1;
    insert into car_model
    values (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'ILX'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'RDX'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'TLX'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Giulia'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Stelvio'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'A6 allroad'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'A7'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'Q3'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'Q5'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'Q8'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'S5'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'S6'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            '3 Series'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'X1'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'X3'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'X5'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'X7'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Enclave'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Encore'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Encore GX'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Envision'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'CT4'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'CT5'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Escalade'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Escalade ESV'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'XT4'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'XT5'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'XT6'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Blazer'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Bolt EV'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Camaro'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Colorado Crew Cab'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Corvette'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Equinox'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Express 3500 Cargo'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Malibu'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Silverado 1500 Crew'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Silverado 2500 HD'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Silverado 3500 HD'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Spark'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Suburban'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Tahoe'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Trailblazer'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Traverse'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Trax'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            '300'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Pacifica'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Voyager'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Challenger'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Charger'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Durango'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            '500X'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Bronco Sport'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'EcoSport'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Edge'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Escape'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Expedition'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Expedition MAX'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Explorer'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'F150 SuperCrew Cab'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'F250 Super Duty'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Mustang'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Ranger SuperCrew'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'G70'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'G80'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'G90'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'GV80'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Acadia'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Canyon Crew Cab'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Canyon Extended Cab'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Sierra 1500 Crew'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Sierra 2500 HD'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Sierra 3500 HD'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Terrain'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Yukon'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Yukon XL'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Accord'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Accord Hybrid'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Civic'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Civic Type R'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'CR-V'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'CR-V Hybrid'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'HR-V'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Insight'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Odyssey'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Passport'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Pilot'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Ridgeline'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Accent'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Elantra'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Ioniq Electric'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Ioniq Hybrid'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Kona'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Kona Electric'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Palisade'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Santa Fe'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Sonata'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Sonata Hybrid'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Tucson'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Veloster'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Venue'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Q50'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'QX50'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'QX80'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'E-PACE'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'I-PACE'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Cherokee'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Compass'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Gladiator'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Grand Cherokee'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Grand Cherokee L'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Renegade'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Wrangler'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Wrangler Unlimited'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Forte'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'K5'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Rio'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Sedona'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Seltos'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Sorento'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Soul'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Sportage'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Stinger'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Telluride'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Discovery'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Range Rover'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Range Rover Sport'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Range Rover Velar'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'ES'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'GX'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'IS'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'LC'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'LS'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'LX'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'NX'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'RC'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'RX'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, 'UX'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Aviator'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Corsair'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Nautilus'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Navigator'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Navigator L'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'CX-3'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'CX-30'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'CX-5'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'CX-9'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'MAZDA3'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'MAZDA6'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'MX-5 Miata'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'MX-5 Miata RF'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'A-Class'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'C-Class'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'G-Class'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'GLA'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'GLB'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'GLC'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'GLE'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Outlander Sport'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Altima'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Frontier Crew Cab'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Frontier King Cab'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Kicks'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'LEAF'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Maxima'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Murano'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'NV3500 HD Cargo'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Rogue'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Sentra'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'TITAN XD Crew Cab'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Versa'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1, '2'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            '718 Boxster'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            '718 Cayman'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            '718 Spyder'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            '911'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Cayenne'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Cayenne Coupe'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Macan'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Panamera'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Taycan'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            '1500 Crew Cab'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            '2500 Crew Cab'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            '2500 Mega Cab'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'ProMaster Cargo Van'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'ProMaster City'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'R1S'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'R1T'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Ascent'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Crosstrek'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Forester'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Impreza'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Legacy'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Outback'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Model S'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Model X'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            '4Runner'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Avalon'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Avalon Hybrid'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Camry'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Camry Hybrid'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'C-HR'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Corolla'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Corolla Hatchback'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Corolla Hybrid'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'GR Supra'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Highlander'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Highlander Hybrid'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Land Cruiser'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Prius Prius Prime'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'RAV4'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'RAV4 Hybrid'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'RAV4 Prime'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Sequoia'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Sienna'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Tacoma Access Cab'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Tacoma Double Cab'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Tundra CrewMax'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Tundra Double Cab'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Venza'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Atlas'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Atlas Cross Sport'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Golf'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Jetta'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Passat'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'Tiguan'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'S90'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'V60'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'V90'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'XC40'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'XC60'),
           (nextval('car_model_seq'), floor(random() * brands_count) + 1,
            'XC90');
end;
$$;