version: "3.3"

services:
    postgres_db:
        image: postgres:13.2
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
            - ./csv:/docker-entrypoint-initdb.d/csv
        ports:
            - 5432:5432
    pgadmin:
        image: dpage/pgadmin4:4.30
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_PORT: 80
        ports:
            - 8080:80
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres_db

volumes:
    db-data:
    pgadmin-data: